[settings]
always_keep_download = false
experimental = true

[settings.npm]
package_manager = "pnpm"

[tools]
go = "latest"
golangci-lint = "latest"
"go:golang.org/x/tools/gopls" = "latest"

rust = "latest"
# faster backend "cargo:".
cargo-binstall = "latest"

node = "latest"
pnpm = "latest"
bun = "latest"
"npm:eslint" = "10"
"npm:opencode-ai" = "latest"
"npm:@kilocode/cli" = "latest"
"npm:@openai/codex" = "latest"
"npm:izteamslots" = "latest"
"npm:skills" = "latest"
"npm:get-shit-done-cc" = "latest"
"npm:@typescript/native-preview" = "beta"
"npm:@google/gemini-cli" = "latest"

python = "latest"
ruff = "latest"
"github:astral-sh/uv" = "latest"
"github:rossmacarthur/sheldon" = "latest"
"github:microsoft/vcpkg-tool" = "2026-03-04"
"github:bitwarden/clients" = "cli-v2026.4.1"
"github:ouch-org/ouch" = "latest"
"github:aristocratos/btop" = "latest"
"github:zeroclaw-labs/zeroclaw" = "latest"

gh = "latest"
vp = "latest"
usage = "latest"
watchexec = "latest"
fzf = "latest"
zoxide = "latest"
claude = "latest"
pandoc = "latest"
ripgrep = { version = "latest", os = ["linux", "macos"] }
pi = "latest"
atuin = "latest"
neovim = "latest"
zellij = "latest"
starship = "latest"
helix = "latest"
chezmoi = "latest"
yazi = "latest"
fd = "latest"
dust = "latest"
mkcert = "latest"
glow = "latest"
age = "latest"
